packages:
  - frontend
  - tools/release

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@tanstack/angular-table@9.1.0"
  - "@tanstack/table-core@9.1.0"
blockExoticSubdeps: true
strictDepBuilds: true
nodeLinker: isolated

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
